spring:
  application:
    name: coffeetech

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/coffeetech
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        check_nullability: true

server:
  address: 0.0.0.0

jwt:
  secret: mysecretkeymysecretkeymysecretkeymysecretkey

front:
  url: http://localhost:3000
  